ID_INFORMATICA = 1
ID_ECONOMIA = 2
ID_DIRITTO = 3
ID_SOCIOLOGIA = 4

VALUE_INFORMATICA = 'Informatica'
VALUE_ECONOMIA = 'Economia'
VALUE_DIRITTO = 'Diritto'
VALUE_SOCIOLOGIA = 'Sociologia'

ID_INSERISCI_VOTO = 1
ID_VEDI_VOTI = 2

VALUE_INSERISCI_VOTO = "Inserisci voto"
VALUE_VEDI_VOTI = "Vedi voti"

MIN_VOTO = 18
MAX_VOTO = 30